###################
#  Fine-tune on Real Fog (pseudo GT)
###################

name: Finetune_RealFog_Restormer
model_type: ImageCleanModel
scale: 1
num_gpu: 1
manual_seed: 100

###################
# Datasets
###################
datasets:
  train:
    name: RealFog_train
    type: Dataset_PairedImage
    dataroot_gt: ./Dehazing/Datasets/myDataset/Real/Finetune/train/gt
    dataroot_lq: ./Dehazing/Datasets/myDataset/Real/Finetune/train/hazy

    geometric_augs: true
    filename_tmpl: '{}'
    io_backend:
      type: disk

    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 1

    mini_batch_sizes: [1]
    iters: [20000]          # Fine-tune：2~3 万 iter 足够
    gt_size: 160
    gt_sizes: [160]
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: RealFog_val
    type: Dataset_PairedImage
    dataroot_gt: ./Dehazing/Datasets/myDataset/Real/Finetune/val/gt
    dataroot_lq: ./Dehazing/Datasets/myDataset/Real/Finetune/val/hazy
    io_backend:
      type: disk

###################
# Network (与大号 SOTS 模型保持一致!)
###################
network_g:
  type: Restormer
  inp_channels: 3
  out_channels: 3
  dim: 48
  num_blocks: [4, 6, 6, 8]
  num_refinement_blocks: 4
  heads: [1, 2, 4, 8]
  ffn_expansion_factor: 2.66
  bias: False
  LayerNorm_type: WithBias
  dual_pixel_task: False

###################
# Paths
###################
path:
  # ★ 用你刚刚训练好的“大模型”作为预训练
  pretrain_network_g: ./experiments/Dehazing_SOTS_Outdoor_Restormer/models/net_g_80000.pth
  strict_load_g: true

  # ★ 这里一定要 ~，表示“新任务从预训练权重开始”，而不是恢复旧状态
  resume_state: ~

  experiments_root: ./experiments/Finetune_RealFog_Restormer

###################
# Training settings
###################
train:
  optim_g:
    type: AdamW
    lr: 1.0e-4          # 比预训练小一档，更温和的 fine-tune
    betas: [0.9, 0.999]
    weight_decay: 0.02

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [20000]
    restart_weights: [1]
    eta_min: 1.0e-6

  total_iter: 20000
  warmup_iter: -1

  use_grad_clip: true
  grad_clip: 0.01

  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean

  mixing_augs:
    mixup: false
    mixup_beta: 1.2
    use_identity: true

###################
# Validation
###################
val:
  val_freq: 2000
  save_img: true

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

###################
# Logger
###################
logger:
  print_freq: 100
  save_checkpoint_freq: 2000
  use_tb_logger: true
  use_wandb: false
  wandb:
    project: Finetune_RealFog
    resume_id: ~

###################
# Distributed
###################
dist_params:
  backend: nccl
  port: 29500
